// GENERATED BY GOBBLEDEEGOOK, TO UPDATE, EDIT messages.*.json AND RERUN 'GOOK'
package gobbledeegook

var T_en_gb = struct {
	foo string
}{"abc"}
var T_en_us = struct {
	foo string
}{"abc"}
var T = T_en_us

func init() { T = T_en_gb }
