package main

import (
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"

	"github.com/julz/gobbledeegook"
)

func main() {
	structs := make([]string, 0)
	filepath.Walk(".", func(path string, info os.FileInfo, err error) error {
		if strings.HasSuffix(path, ".json") && strings.HasPrefix(path, "messages.") {
			language := strings.Split(path, ".")[1]

			messages, err := ioutil.ReadFile(path)
			if err != nil {
				panic(err)
			}

			structs = append(structs, gobbledeegook.Generate("T_"+language, string(messages)))
		}

		comment := "// GENERATED BY GOBBLEDEEGOOK, TO UPDATE, EDIT messages.*.json AND RERUN 'GOOK'"
		init := "var T = T_en_us\n\nfunc init() { T = T_en_gb }"
		ioutil.WriteFile("messages.go", []byte(comment+"\npackage gobbledeegook\n\n"+strings.Join(structs, "\n")+"\n"+init+"\n"), 0755)

		return nil
	})
}
